namespace AddonStore.Web.Services;

/// <summary>
/// Texts of the invitation mail and the invitation page in the 21 Power PDF
/// languages. Placeholders: {name}, {email}, {date}.
/// </summary>
public static class SendToTexts
{
    public sealed record T(string Subject, string Intro, string Button, string Footer, string Title, string Ask,
                           string Accept, string Decline, string AcceptedTitle, string AcceptedText, string DeclinedTitle,
                           string DeclinedText, string NotFoundTitle, string NotFoundText, string NotOpenText, string Unavailable);

    private static readonly Dictionary<string, T> All = new()
    {
        ["en"] = new("{name} wants to exchange documents with you in Power PDF",
            "{name} ({email}) invites you to exchange documents with Send to in Tungsten Power PDF.",
            "View invitation", "If you do not know {name}, ignore this e-mail. The invitation expires on {date}.",
            "Invitation", "{name} ({email}) wants to exchange documents with you in Power PDF.", "Accept", "Decline",
            "Accepted", "You can now exchange documents with {name}. If you have not yet done so, install Send to from the Add-on Store in Power PDF.",
            "Declined", "The invitation was declined.", "Invitation not found", "The link is invalid or has expired.",
            "This invitation is no longer open.", "Send to is currently not available."),
        ["de"] = new("{name} möchte mit Ihnen Dokumente in Power PDF austauschen",
            "{name} ({email}) lädt Sie ein, mit „Senden an“ in Tungsten Power PDF Dokumente auszutauschen.",
            "Einladung ansehen", "Wenn Sie {name} nicht kennen, ignorieren Sie diese E-Mail. Die Einladung verfällt am {date}.",
            "Einladung", "{name} ({email}) möchte mit Ihnen Dokumente in Power PDF austauschen.", "Annehmen", "Ablehnen",
            "Angenommen", "Sie können jetzt mit {name} Dokumente austauschen. Falls noch nicht geschehen: Installieren Sie „Senden an“ über den Add-on Store in Power PDF.",
            "Abgelehnt", "Die Einladung wurde abgelehnt.", "Einladung nicht gefunden", "Der Link ist ungültig oder abgelaufen.",
            "Diese Einladung ist nicht mehr offen.", "„Senden an“ ist derzeit nicht verfügbar."),
        ["fr"] = new("{name} souhaite échanger des documents avec vous dans Power PDF",
            "{name} ({email}) vous invite à échanger des documents avec Envoyer à dans Tungsten Power PDF.",
            "Voir l’invitation", "Si vous ne connaissez pas {name}, ignorez cet e-mail. L’invitation expire le {date}.",
            "Invitation", "{name} ({email}) souhaite échanger des documents avec vous dans Power PDF.", "Accepter", "Refuser",
            "Acceptée", "Vous pouvez maintenant échanger des documents avec {name}. Si ce n’est pas encore fait, installez Envoyer à depuis l’Add-on Store dans Power PDF.",
            "Refusée", "L’invitation a été refusée.", "Invitation introuvable", "Le lien n’est pas valide ou a expiré.",
            "Cette invitation n’est plus ouverte.", "Envoyer à n’est pas disponible actuellement."),
        ["it"] = new("{name} vuole scambiare documenti con te in Power PDF",
            "{name} ({email}) ti invita a scambiare documenti con Invia a in Tungsten Power PDF.",
            "Visualizza invito", "Se non conosci {name}, ignora questa e-mail. L’invito scade il {date}.",
            "Invito", "{name} ({email}) vuole scambiare documenti con te in Power PDF.", "Accetta", "Rifiuta",
            "Accettato", "Ora puoi scambiare documenti con {name}. Se non l’hai ancora fatto, installa Invia a dall’Add-on Store in Power PDF.",
            "Rifiutato", "L’invito è stato rifiutato.", "Invito non trovato", "Il link non è valido o è scaduto.",
            "Questo invito non è più aperto.", "Invia a non è al momento disponibile."),
        ["es"] = new("{name} quiere intercambiar documentos contigo en Power PDF",
            "{name} ({email}) te invita a intercambiar documentos con Enviar a en Tungsten Power PDF.",
            "Ver invitación", "Si no conoces a {name}, ignora este correo. La invitación caduca el {date}.",
            "Invitación", "{name} ({email}) quiere intercambiar documentos contigo en Power PDF.", "Aceptar", "Rechazar",
            "Aceptada", "Ya puedes intercambiar documentos con {name}. Si aún no lo has hecho, instala Enviar a desde el Add-on Store en Power PDF.",
            "Rechazada", "La invitación se ha rechazado.", "Invitación no encontrada", "El enlace no es válido o ha caducado.",
            "Esta invitación ya no está abierta.", "Enviar a no está disponible en este momento."),
        ["nl"] = new("{name} wil documenten met u uitwisselen in Power PDF",
            "{name} ({email}) nodigt u uit om documenten uit te wisselen met Verzenden naar in Tungsten Power PDF.",
            "Uitnodiging bekijken", "Als u {name} niet kent, negeer deze e-mail dan. De uitnodiging verloopt op {date}.",
            "Uitnodiging", "{name} ({email}) wil documenten met u uitwisselen in Power PDF.", "Accepteren", "Weigeren",
            "Geaccepteerd", "U kunt nu documenten uitwisselen met {name}. Installeer Verzenden naar via de Add-on Store in Power PDF als u dat nog niet hebt gedaan.",
            "Geweigerd", "De uitnodiging is geweigerd.", "Uitnodiging niet gevonden", "De link is ongeldig of verlopen.",
            "Deze uitnodiging is niet meer open.", "Verzenden naar is momenteel niet beschikbaar."),
        ["pt"] = new("{name} quer trocar documentos com você no Power PDF",
            "{name} ({email}) convida você a trocar documentos com Enviar para no Tungsten Power PDF.",
            "Ver convite", "Se você não conhece {name}, ignore este e-mail. O convite expira em {date}.",
            "Convite", "{name} ({email}) quer trocar documentos com você no Power PDF.", "Aceitar", "Recusar",
            "Aceito", "Agora você pode trocar documentos com {name}. Se ainda não fez isso, instale Enviar para pela Add-on Store no Power PDF.",
            "Recusado", "O convite foi recusado.", "Convite não encontrado", "O link é inválido ou expirou.",
            "Este convite não está mais aberto.", "Enviar para não está disponível no momento."),
        ["da"] = new("{name} vil udveksle dokumenter med dig i Power PDF",
            "{name} ({email}) inviterer dig til at udveksle dokumenter med Send til i Tungsten Power PDF.",
            "Se invitation", "Hvis du ikke kender {name}, kan du ignorere denne e-mail. Invitationen udløber den {date}.",
            "Invitation", "{name} ({email}) vil udveksle dokumenter med dig i Power PDF.", "Accepter", "Afvis",
            "Accepteret", "Du kan nu udveksle dokumenter med {name}. Installer Send til fra Add-on Store i Power PDF, hvis du ikke allerede har gjort det.",
            "Afvist", "Invitationen blev afvist.", "Invitationen blev ikke fundet", "Linket er ugyldigt eller udløbet.",
            "Denne invitation er ikke længere åben.", "Send til er ikke tilgængelig i øjeblikket."),
        ["fi"] = new("{name} haluaa vaihtaa asiakirjoja kanssasi Power PDF:ssä",
            "{name} ({email}) kutsuu sinut vaihtamaan asiakirjoja Lähetä-toiminnolla Tungsten Power PDF:ssä.",
            "Näytä kutsu", "Jos et tunne henkilöä {name}, voit jättää tämän viestin huomiotta. Kutsu vanhenee {date}.",
            "Kutsu", "{name} ({email}) haluaa vaihtaa asiakirjoja kanssasi Power PDF:ssä.", "Hyväksy", "Hylkää",
            "Hyväksytty", "Voit nyt vaihtaa asiakirjoja henkilön {name} kanssa. Asenna Lähetä Power PDF:n Add-on Storesta, jos et ole vielä tehnyt sitä.",
            "Hylätty", "Kutsu hylättiin.", "Kutsua ei löytynyt", "Linkki on virheellinen tai vanhentunut.",
            "Tämä kutsu ei ole enää avoinna.", "Lähetä ei ole tällä hetkellä käytettävissä."),
        ["nb"] = new("{name} vil utveksle dokumenter med deg i Power PDF",
            "{name} ({email}) inviterer deg til å utveksle dokumenter med Send til i Tungsten Power PDF.",
            "Vis invitasjonen", "Hvis du ikke kjenner {name}, kan du se bort fra denne e-posten. Invitasjonen utløper {date}.",
            "Invitasjon", "{name} ({email}) vil utveksle dokumenter med deg i Power PDF.", "Godta", "Avslå",
            "Godtatt", "Du kan nå utveksle dokumenter med {name}. Installer Send til fra Add-on Store i Power PDF hvis du ikke allerede har gjort det.",
            "Avslått", "Invitasjonen ble avslått.", "Fant ikke invitasjonen", "Lenken er ugyldig eller utløpt.",
            "Denne invitasjonen er ikke lenger åpen.", "Send til er ikke tilgjengelig for øyeblikket."),
        ["sv"] = new("{name} vill utbyta dokument med dig i Power PDF",
            "{name} ({email}) bjuder in dig att utbyta dokument med Skicka till i Tungsten Power PDF.",
            "Visa inbjudan", "Om du inte känner {name} kan du ignorera det här e-postmeddelandet. Inbjudan går ut den {date}.",
            "Inbjudan", "{name} ({email}) vill utbyta dokument med dig i Power PDF.", "Acceptera", "Avböj",
            "Accepterad", "Nu kan du utbyta dokument med {name}. Installera Skicka till från Add-on Store i Power PDF om du inte redan har gjort det.",
            "Avböjd", "Inbjudan avböjdes.", "Inbjudan hittades inte", "Länken är ogiltig eller har gått ut.",
            "Den här inbjudan är inte längre öppen.", "Skicka till är inte tillgängligt för tillfället."),
        ["pl"] = new("{name} chce wymieniać się z Tobą dokumentami w Power PDF",
            "{name} ({email}) zaprasza Cię do wymiany dokumentów za pomocą funkcji Wyślij do w Tungsten Power PDF.",
            "Zobacz zaproszenie", "Jeśli nie znasz osoby {name}, zignoruj tę wiadomość. Zaproszenie wygasa {date}.",
            "Zaproszenie", "{name} ({email}) chce wymieniać się z Tobą dokumentami w Power PDF.", "Akceptuj", "Odrzuć",
            "Zaakceptowano", "Możesz teraz wymieniać dokumenty z osobą {name}. Jeśli jeszcze tego nie zrobiono, zainstaluj Wyślij do z Add-on Store w Power PDF.",
            "Odrzucono", "Zaproszenie zostało odrzucone.", "Nie znaleziono zaproszenia", "Link jest nieprawidłowy lub wygasł.",
            "To zaproszenie nie jest już otwarte.", "Funkcja Wyślij do jest obecnie niedostępna."),
        ["cs"] = new("{name} si s vámi chce vyměňovat dokumenty v Power PDF",
            "{name} ({email}) vás zve k výměně dokumentů pomocí funkce Odeslat v Tungsten Power PDF.",
            "Zobrazit pozvánku", "Pokud uživatele {name} neznáte, tento e-mail ignorujte. Platnost pozvánky vyprší {date}.",
            "Pozvánka", "{name} ({email}) si s vámi chce vyměňovat dokumenty v Power PDF.", "Přijmout", "Odmítnout",
            "Přijato", "Nyní si můžete vyměňovat dokumenty s uživatelem {name}. Pokud jste to ještě neudělali, nainstalujte funkci Odeslat z Add-on Store v Power PDF.",
            "Odmítnuto", "Pozvánka byla odmítnuta.", "Pozvánka nebyla nalezena", "Odkaz je neplatný nebo jeho platnost vypršela.",
            "Tato pozvánka již není otevřená.", "Funkce Odeslat není momentálně k dispozici."),
        ["hu"] = new("{name} dokumentumokat szeretne cserélni Önnel a Power PDF-ben",
            "{name} ({email}) meghívja Önt, hogy a Küldés funkcióval dokumentumokat cseréljenek a Tungsten Power PDF-ben.",
            "Meghívó megtekintése", "Ha nem ismeri {name} nevű felhasználót, hagyja figyelmen kívül ezt az e-mailt. A meghívó lejár: {date}.",
            "Meghívó", "{name} ({email}) dokumentumokat szeretne cserélni Önnel a Power PDF-ben.", "Elfogadás", "Elutasítás",
            "Elfogadva", "Most már cserélhet dokumentumokat vele: {name}. Ha még nem tette meg, telepítse a Küldés funkciót a Power PDF Add-on Store-jából.",
            "Elutasítva", "A meghívót elutasították.", "A meghívó nem található", "A hivatkozás érvénytelen vagy lejárt.",
            "Ez a meghívó már nem nyitott.", "A Küldés funkció jelenleg nem érhető el."),
        ["ru"] = new("{name} хочет обмениваться с вами документами в Power PDF",
            "{name} ({email}) приглашает вас обмениваться документами с помощью функции «Отправить» в Tungsten Power PDF.",
            "Открыть приглашение", "Если вы не знаете пользователя {name}, проигнорируйте это письмо. Срок действия приглашения истекает {date}.",
            "Приглашение", "{name} ({email}) хочет обмениваться с вами документами в Power PDF.", "Принять", "Отклонить",
            "Принято", "Теперь вы можете обмениваться документами с пользователем {name}. Если вы ещё этого не сделали, установите «Отправить» из Add-on Store в Power PDF.",
            "Отклонено", "Приглашение отклонено.", "Приглашение не найдено", "Ссылка недействительна или устарела.",
            "Это приглашение больше не открыто.", "Функция «Отправить» сейчас недоступна."),
        ["tr"] = new("{name}, Power PDF'te sizinle belge paylaşmak istiyor",
            "{name} ({email}), sizi Tungsten Power PDF'te Gönder özelliğiyle belge paylaşmaya davet ediyor.",
            "Daveti görüntüle", "{name} adlı kişiyi tanımıyorsanız bu e-postayı yok sayın. Davetin süresi {date} tarihinde dolar.",
            "Davet", "{name} ({email}), Power PDF'te sizinle belge paylaşmak istiyor.", "Kabul et", "Reddet",
            "Kabul edildi", "Artık {name} ile belge paylaşabilirsiniz. Henüz yapmadıysanız Gönder özelliğini Power PDF'teki Add-on Store'dan yükleyin.",
            "Reddedildi", "Davet reddedildi.", "Davet bulunamadı", "Bağlantı geçersiz veya süresi dolmuş.",
            "Bu davet artık açık değil.", "Gönder özelliği şu anda kullanılamıyor."),
        ["zh-Hans"] = new("{name} 希望在 Power PDF 中与您交换文档",
            "{name}（{email}）邀请您使用 Tungsten Power PDF 中的“发送到”功能交换文档。",
            "查看邀请", "如果您不认识 {name}，请忽略此邮件。邀请将于 {date} 过期。",
            "邀请", "{name}（{email}）希望在 Power PDF 中与您交换文档。", "接受", "拒绝",
            "已接受", "您现在可以与 {name} 交换文档。如果尚未安装，请从 Power PDF 的 Add-on Store 安装“发送到”。",
            "已拒绝", "邀请已被拒绝。", "未找到邀请", "链接无效或已过期。",
            "此邀请已不再有效。", "“发送到”目前不可用。"),
        ["zh-Hant"] = new("{name} 希望在 Power PDF 中與您交換文件",
            "{name}（{email}）邀請您使用 Tungsten Power PDF 中的「傳送至」功能交換文件。",
            "檢視邀請", "如果您不認識 {name}，請忽略此郵件。邀請將於 {date} 到期。",
            "邀請", "{name}（{email}）希望在 Power PDF 中與您交換文件。", "接受", "拒絕",
            "已接受", "您現在可以與 {name} 交換文件。如果尚未安裝，請從 Power PDF 的 Add-on Store 安裝「傳送至」。",
            "已拒絕", "邀請已被拒絕。", "找不到邀請", "連結無效或已過期。",
            "此邀請已不再有效。", "「傳送至」目前無法使用。"),
        ["ja"] = new("{name} さんが Power PDF で文書のやり取りを希望しています",
            "{name} さん（{email}）から、Tungsten Power PDF の「送信」機能で文書をやり取りするよう招待が届きました。",
            "招待を表示", "{name} さんに心当たりがない場合は、このメールを無視してください。招待の有効期限は {date} です。",
            "招待", "{name} さん（{email}）が Power PDF で文書のやり取りを希望しています。", "承諾", "辞退",
            "承諾しました", "{name} さんと文書をやり取りできるようになりました。まだの場合は、Power PDF の Add-on Store から「送信」をインストールしてください。",
            "辞退しました", "招待を辞退しました。", "招待が見つかりません", "リンクが無効か、有効期限が切れています。",
            "この招待はすでに無効です。", "「送信」は現在ご利用いただけません。"),
        ["ko"] = new("{name}님이 Power PDF에서 문서를 주고받기를 원합니다",
            "{name}님({email})이 Tungsten Power PDF의 보내기 기능으로 문서를 주고받도록 초대했습니다.",
            "초대 보기", "{name}님을 모르는 경우 이 메일을 무시하세요. 초대는 {date}에 만료됩니다.",
            "초대", "{name}님({email})이 Power PDF에서 문서를 주고받기를 원합니다.", "수락", "거절",
            "수락됨", "이제 {name}님과 문서를 주고받을 수 있습니다. 아직 설치하지 않았다면 Power PDF의 Add-on Store에서 보내기를 설치하세요.",
            "거절됨", "초대를 거절했습니다.", "초대를 찾을 수 없음", "링크가 잘못되었거나 만료되었습니다.",
            "이 초대는 더 이상 유효하지 않습니다.", "보내기 기능을 현재 사용할 수 없습니다."),
        ["ar"] = new("يرغب {name} في تبادل المستندات معك في Power PDF",
            "يدعوك {name} ({email}) إلى تبادل المستندات باستخدام ميزة الإرسال في Tungsten Power PDF.",
            "عرض الدعوة", "إذا كنت لا تعرف {name}، فتجاهل هذه الرسالة. تنتهي صلاحية الدعوة في {date}.",
            "دعوة", "يرغب {name} ({email}) في تبادل المستندات معك في Power PDF.", "قبول", "رفض",
            "تم القبول", "يمكنك الآن تبادل المستندات مع {name}. إذا لم تكن قد فعلت ذلك بعد، فثبّت ميزة الإرسال من Add-on Store في Power PDF.",
            "تم الرفض", "تم رفض الدعوة.", "لم يتم العثور على الدعوة", "الرابط غير صالح أو منتهي الصلاحية.",
            "لم تعد هذه الدعوة مفتوحة.", "ميزة الإرسال غير متاحة حاليًا."),
    };

    public static T For(string? lang) => lang is not null && All.TryGetValue(lang, out var t) ? t : All["en"];

    public static bool IsRtl(string? lang) => lang == "ar";

    public static string Fill(string s, string name, string email, string date) =>
        s.Replace("{name}", name).Replace("{email}", email).Replace("{date}", date);

    /// <summary>All 21 languages present (checked by the docs/rules test).</summary>
    public static IEnumerable<string> Languages => All.Keys;
}
